// import "./globals.css";
import "../styles/global.scss";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import StyledJsxRegistry from "./registry";
import { GlobalStyle } from "./GlobalStyles";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalStyle />
        <StyledJsxRegistry>
          <Header />
          {children}
          <Footer />
        </StyledJsxRegistry>
      </body>
    </html>
  );
}
